name: fruit_hub
description: Order Freshest Fruit Salad

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  provider: ^6.0.4
  intl: ^0.17.0
  google_maps_flutter: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
     - assets/images/
     - assets/icons/

  fonts:
     - family: Brandon-Grotesque
       fonts:
         - asset: assets/fonts/Brandon-Grotesque/brandon-grotesque-light.otf
         - asset: assets/fonts/Brandon-Grotesque/brandon-grotesque-regular-italic.otf
         - asset: assets/fonts/Brandon-Grotesque/brandon-grotesque-bold-italic.otf
           weight: 800
